/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jadson' at '11/06/16 00:29' with Gradle 2.13
 *
 * @author jadson, @date 11/06/16 00:29
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
